# Generated by Django 4.1.4 on 2023-01-01 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='createdAt',
            field=models.DateField(default=datetime.datetime(2023, 1, 1, 11, 27, 24, 782462)),
        ),
    ]
